services:

  www:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "www_${COMPOSE_PROJECT_NAME}"
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html:rw
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${SSL_DIR}:/etc/apache2/ssl/
      - ${VHOSTS_DIR}:/etc/apache2/sites-available
      - ${APACHE_LOG_DIR}:/var/log/apache2
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT}
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - database
    networks:
    - gsbfrais

  database:
    image: mariadb:lts
    container_name: "db_${COMPOSE_PROJECT_NAME}"
    volumes:
      - ${MYSQL_INITDB_DIR}:/docker-entrypoint-initdb.d
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_LOG_DIR}:/var/log/mysql      
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      command: --sql_mode="ONLY_FULL_GROUP_BY"
    networks:
      - gsbfrais

  phpmyadmin:
    image: phpmyadmin
    container_name: "pma_${COMPOSE_PROJECT_NAME}"
    depends_on:
      - database
    ports:
      - "${HOST_MACHINE_PMA_PORT}:80"
      - "${HOST_MACHINE_PMA_SECURE_PORT}:443"
    environment:
      PMA_HOST: database
      PMA_PORT: "${HOST_MACHINE_MYSQL_PORT}"
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
    networks:
      - gsbfrais
    volumes:
      - /sessions

networks:
  gsbfrais:

volumes:
  mysql_data:
